# finn_scraper/config/config.yaml

base_url: "https://www.finn.no/realestate/homes/search.html?location=0.20061"
max_page: 50
scrape_delay_min: 0.5
scrape_delay_max: 1.5
database_name: "finn_properties.db"
csv_export_name: "data/finn_properties2.csv"
finn_codes_csv_export_name: "data/finn_codes.csv"

ad_url: "https://www.finn.no/realestate/homes/ad.html?finnkode={}"
finn_code_selector: 'a[href*="finnkode="]' # CSS selector to find links containing Finn codes