# finn_scraper/config/logging.yaml

version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: 'logs/finn_scraper.log'
    encoding: utf-8
loggers:
  scraper:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]